### PR TITLE
Feature/flutter admob example

### PR DESCRIPTION
**Pull request by ricardobrg**
Implements the example for AdMob initialization with UMP.

### CODE REVIEW

**Comment by ricardobrg** [comment]
@Harshit933 Thank you for your contribution! Adding here some comments about the code:

- https://github.com/tiki/examples/blob/feature/flutter-admob-example/flutter/admob/lib/home_screen.dart#L107
The `loadAd` function should be just called once on widget initialization. If it is done in the `onTap` callback, it will be triggered in every button tap, causing unnecessary calls and potencial errors. You can call it in the initState as in [this example](https://codelabs.developers.google.com/codelabs/admob-ads-in-flutter?hl=en#8)

- https://github.com/tiki/examples/blob/feature/flutter-admob-example/flutter/admob/lib/home_screen.dart#L89
In the `onAccept` callback you are using the `loadAd` method again. 

- https://github.com/tiki/examples/blob/feature/flutter-admob-example/flutter/admob/lib/home_screen.dart#L64
looks like this method is not used anywhere and could be removed

- https://github.com/tiki/examples/blob/feature/flutter-admob-example/flutter/admob/lib/home_screen.dart#L77-L92
Avoid doing anything that is not UI related in the build method, because we don't have any control of how many times it will be called or when. In a stateful widget, the best option is to use the initState method, that is called only once, or in the constructor of the Widget class.

-  https://github.com/tiki/examples/blob/36859b51b9ce14acb04e67b3693b5aa53d5872b5/flutter/admob/lib/home_screen.dart#L133
We don't need the settings button anymore. You can remove it.

- https://github.com/tiki/examples/blob/36859b51b9ce14acb04e67b3693b5aa53d5872b5/flutter/admob/lib/home_screen.dart#L35
Is this method necessary?

**Comment by Harshit933** [comment]
The thing with `loadAd` in `initState` is that the ad can only be loaded once on the page and after that ad is ran. We have to re start the app to load another ad. I agree with you that it would cause potential errors in the app when we are calling the same functions in the `onTap` and `onAccept` method . What can we do here?

`loadBanner` method was used to generate the id for the test ads to run on the test devices (in `main.dart` `MobileAds.instance.updateRequestConfiguration(RequestConfiguration(
      testDeviceIds: ['A9BFA2CD58BFD0F412F9B597C5C5B380']));` . We can still have it to generate test device id to test the ads. What do you think?

`_setFullScreen` method would make more sense in the real life applications. Sure I'll remove it.

Also I should've kept in mind about the build function and it's ability to refresh its content everytime the build reconstructs. I'll switch the offer to `initState`.

**Comment by ricardobrg** [comment]
@Harshit933 
> The thing with `loadAd` in `initState` is that the ad can only be loaded once on the page and after that ad is ran. We have to re start the app to load another ad. I agree with you that it would cause potential errors in the app when we are calling the same functions in the `onTap` and `onAccept` method . What can we do here?
Got it, we need to load a new ad, that is why you call in `onAccept`. The issue here is that we don't know how long will it take to load the ad. Since we are loading one ad per screen, what do you think about using the Navigator pop from reward screen to load a new ad? We could load an ad in `initState`, and load a new one when the user comes back. In line 58 we can await on `Navigator.push` and then call `_loadAd` again.

**Comment by ricardobrg** [comment]
@Harshit933 About the `loadBanner` method, it is not called anywhere. That is why I asked about it. If everything works without it, maybe it is unnecessary.

**Comment by Harshit933** [comment]
Sure, I will update the code tomorrow only. Thank you for the feedback!

**Comment by ricardobrg** [comment]
@Harshit933 thanks for your PR. I will grab it from here since some requirements from the original issue changed.

**Comment by Harshit933** [comment]
Sure, let me know if there is anything that I can do

**Comment by ricardobrg** [comment]
@mike-audi Flutter is ready for review

**Pull request merged**
